# Generated by Django 2.2.14 on 2024-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240411_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.FloatField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
